# Cloud Scheduler設定ファイル
# 使用方法: gcloud scheduler jobs create http JOB_NAME --config-from-file=scheduler-config.yaml

scheduler_jobs:
  # AI提案生成ジョブ（夕方17時）
  - name: "ai-proposal-generation-evening"
    description: "夕方のAI提案生成ジョブ（17時）"
    schedule: "0 17 * * *"  # 毎日17時に実行
    time_zone: "Asia/Tokyo"
    http_target:
      uri: "https://YOUR_CLOUD_RUN_URL/api/v1/generate-ai-proposals"
      http_method: "POST"
      headers:
        Content-Type: "application/json"
      body: |
        {
          "max_proposals_per_user": 3,
          "force_generation": false
        }
      oidc_token:
        service_account_email: "your-service-account@your-project.iam.gserviceaccount.com"
    retry_config:
      retry_count: 2
      max_retry_duration: "1200s"
      min_backoff_duration: "10s"
      max_backoff_duration: "300s"

  # 毎日のキャッシュクリアジョブ（深夜2時）
  - name: "cache-cleanup-daily"
    description: "毎日のキャッシュクリーンアップジョブ（2時）"
    schedule: "0 2 * * *"  # 毎日2時に実行
    time_zone: "Asia/Tokyo"
    http_target:
      uri: "https://YOUR_CLOUD_RUN_URL/admin/cache/clear"
      http_method: "POST"
      oidc_token:
        service_account_email: "your-service-account@your-project.iam.gserviceaccount.com"
    retry_config:
      retry_count: 1
      max_retry_duration: "600s" 